name: Sync Algolia

on:
  push:
    branches:
      - 'main'

jobs:
  algolia:
    runs-on: ubuntu-latest
    name: Algolia Sync
    steps:
      - uses: actions/checkout@v2

      - uses: opstrace/algolia-docs-sync@v1.0.2
        with:
          algoliaId: '2NR3GMOKDP'
          algoliaKey: ${{ secrets.ALGOLIA_API_KEY }}
          algoliaIndex: 'tina-docusaurus'