name: Algolia Upload Records
on:
  [push]
jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Algolia Docsearch Uploader
        uses: guzhongren/algolia-docsearch-upload-action@v2.0.0
        
        env:
          FILE_PATH: "https://raw.githubusercontent.com/oschcz/TinaDocusaurus/main/algolia.json"
          APPLICATION_ID: "2NR3GMOKDP"
          ADMIN_API_KEY: "d14cce60885421e78fd7a878cc3733b8"
          INDEX_NAME: "tina-docusaurus"