name: Algolia Indexer

on:
  push:
    branches: [ main ]

jobs:
  - uses: rxrw/algolia-index-uploader@v1
  with:
    index_path: "algolia.json"
    algolia_index_id: "2NR3GMOKDP"
    algolia_index_name: "tina-docusaurus"
    algolia_index_admin_key: "d14cce60885421e78fd7a878cc3733b8"