name: Algolia Upload Records
on:
  [push]
jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Algolia Docsearch Uploader
        uses: guzhongren/algolia-docsearch-upload-action@v2.0.0
        env:
          FILE_PATH: "./algolia.json"
          APPLICATION_ID: "2NR3GMOKDP"
          ADMIN_API_KEY: "eaf33e5fceded83858579d69cdc337bb"
          INDEX_NAME: "tina-docusaurus"