name: <action_name>

on:
  push:
    branches: [ master ]

jobs:
  upload_algolia_index:
    runs-on: ubuntu-latest
    name: Update Algolia Index
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: tilburgsciencehub/algolia-uploader@master
      with:
        # Algolia app id
        app_id: '2NR3GMOKDP'
        # Secret token in the organization's 'Setting > Secrets'
        admin_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        # The index name
        index_name: 'tina-docusaurus'
        # The index file path relative to repo root.
        index_file_path: algolia.json